import { calculateIWDAResult } from "./iwda/scoring";
import { IWDA_QUESTIONS } from "./iwda/questions";
import {
  createVerificationToken,
  hashToken,
  isValidEmail,
  normalizeEmail,
  verificationEmailHtml,
  verificationEmailText,
  verificationExpiry,
  verificationUrl,
  MAX_ATTEMPTS,
} from "./identity";

type ParticipantType = "adult" | "minor";
type Env = { DB: D1Database; RESEND_API_KEY?: string; ASSETS?: Fetcher };
type Participant = { id:string; participant_type:ParticipantType; full_name:string; email:string; phone:string; status:string; email_verified_at:string|null; phone_verified_at:string|null; guardian_authorized_at:string|null };
type Attempt = { id:string; user_id:string|null; participant_id:string|null; anonymous_session_id:string|null; status:string };
type Result = { id:string; attempt_id:string; user_id:string|null; innovation_readiness_index:number|null; traits:string|null; result_data:string|null; created_at:string };
type JsonObject = Record<string, unknown>;

const json=(data:unknown,status=200)=>Response.json(data,{status});
function fail(message:string,status=400,details?:unknown){if(details)console.error(message,details);return json({error:message},status)}
async function body(request:Request):Promise<JsonObject>{const value:unknown=await request.json();if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Request body must be a JSON object");return value as JsonObject}
function text(value:unknown):string{return typeof value==="string"?value.trim():""}
function participantPublic(p:Participant){return{id:p.id,participant_type:p.participant_type,status:p.status,email_verified:Boolean(p.email_verified_at),guardian_authorized:Boolean(p.guardian_authorized_at)}}
function resultPublic(r:Result){let resultData:unknown=null;let traits:unknown[]=[];try{resultData=r.result_data?JSON.parse(r.result_data):null}catch{}try{const parsed=r.traits?JSON.parse(r.traits):[];traits=Array.isArray(parsed)?parsed:[]}catch{}return{id:r.id,attempt_id:r.attempt_id,user_id:r.user_id,innovation_readiness_index:r.innovation_readiness_index,traits,result_data:resultData,created_at:r.created_at}}

async function sendViaResend(env:Env,participantName:string,destination:string,verifyUrl:string):Promise<void>{
  const key=env.RESEND_API_KEY?.trim();
  if(!key)throw new Error("RESEND_API_KEY is not configured");
  const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Authorization":`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from:"Innovators World <verify@innovatorsworld.org>",to:[destination],subject:"Verify your Innovators World email",html:verificationEmailHtml(participantName,verifyUrl),text:verificationEmailText(participantName,verifyUrl)})});
  if(!response.ok){let detail="Resend rejected the email";try{const data=await response.json() as {message?:string;name?:string};detail=data.message||data.name||detail}catch{}throw new Error(`RESEND_SEND_FAILED: ${detail} (HTTP ${response.status})`)}
}

async function sendVerificationEmail(env:Env,request:Request,participantName:string,participantType:ParticipantType,participantId:string,destination:string):Promise<string>{
  const token=createVerificationToken();const now=new Date().toISOString();const expiresAt=verificationExpiry();const challengeId=crypto.randomUUID();const channel=participantType==="minor"?"guardian_email":"email";const verifyUrl=verificationUrl(request,token);
  await env.DB.prepare(`INSERT INTO identity_verification_challenges (id,participant_id,channel,destination,code_hash,expires_at,created_at) VALUES (?,?,?,?,?,?,?)`).bind(challengeId,participantId,channel,destination,await hashToken(token),expiresAt,now).run();
  try{await sendViaResend(env,participantName,destination,verifyUrl)}catch(error){console.error("Resend email send failed",error);throw new Error(error instanceof Error?error.message:String(error))}
  return expiresAt;
}

async function register(request:Request,env:Env):Promise<Response>{let stage="start";try{const b=await body(request);const participantType=text(b.participant_type) as ParticipantType;const fullName=text(b.full_name);const email=normalizeEmail(b.email);const guardianName=text(b.parent_guardian_name);const guardianEmail=normalizeEmail(b.parent_guardian_email);const consentVersion=text(b.consent_version);if(participantType!=="adult"&&participantType!=="minor")return fail("Please select Adult / 18+ or Under 18.");if(!fullName)return fail("Full name is required.");if(!consentVersion)return fail("Assessment terms must be accepted.");const destination=participantType==="minor"?guardianEmail:email;if(!destination||!isValidEmail(destination))return fail("A valid email address is required.");if(participantType==="minor"&&!guardianName)return fail("Parent or guardian name is required for participants under 18.");if(!env.RESEND_API_KEY)return fail("Email verification is not configured on the Worker.",503);
stage="participant lookup";const existing=await env.DB.prepare(`SELECT id,participant_type,full_name,email,phone,status,email_verified_at,phone_verified_at,guardian_authorized_at FROM participants WHERE lower(email)=? LIMIT 1`).bind(destination).first<Participant>();let participantId:string;
if(existing){const verified=Boolean(existing.email_verified_at)&&(existing.participant_type!=="minor"||Boolean(existing.guardian_authorized_at));if(verified&&existing.status==="active")return json({status:"ok",participant_id:existing.id,participant:participantPublic(existing),verification_required:false,verified:true,existing:true});participantId=existing.id;stage="participant update";const now=new Date().toISOString();await env.DB.prepare(`UPDATE participants SET participant_type=?,full_name=?,parent_guardian_name=?,parent_guardian_email=?,consent_version=?,consent_at=?,email_verified_at=NULL,guardian_authorized_at=NULL,status='pending_verification',updated_at=? WHERE id=?`).bind(participantType,fullName,participantType==="minor"?guardianName:null,participantType==="minor"?destination:null,consentVersion,now,now,participantId).run()}else{participantId=crypto.randomUUID();const now=new Date().toISOString();stage="participant insert";await env.DB.prepare(`INSERT INTO participants (id,participant_type,full_name,email,phone,date_of_birth,age_band,parent_guardian_name,parent_guardian_email,parent_guardian_phone,consent_version,consent_at,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(participantId,participantType,fullName,destination,"",text(b.date_of_birth)||null,text(b.age_band)||null,participantType==="minor"?guardianName:null,participantType==="minor"?destination:null,"",consentVersion,now,"pending_verification",now,now).run();stage="consent insert";await env.DB.prepare(`INSERT INTO participant_consents (id,participant_id,consent_type,version,granted_at) VALUES (?,?,?,?,?)`).bind(crypto.randomUUID(),participantId,participantType==="minor"?"guardian_authorization":"assessment",consentVersion,now).run()}
stage="verification email";const expiresAt=await sendVerificationEmail(env,request,fullName,participantType,participantId,destination);return json({status:"ok",participant_id:participantId,verification_required:true,expires_at:expiresAt,existing:Boolean(existing)},existing?200:201)}catch(error){console.error("IWDA registration failed",{stage,error});const message=error instanceof Error?error.message:String(error);return fail(`Unable to register participant. Stage: ${stage}. ${message}`,500)}}

async function verifyEmail(request:Request,env:Env):Promise<Response>{const token=new URL(request.url).searchParams.get("token")?.trim()||"";if(!token)return fail("Invalid verification link.",400);try{const challenge=await env.DB.prepare(`SELECT id,participant_id,channel,expires_at,verified_at,attempts FROM identity_verification_challenges WHERE code_hash=? ORDER BY created_at DESC LIMIT 1`).bind(await hashToken(token)).first<{id:string;participant_id:string;channel:string;expires_at:string;verified_at:string|null;attempts:number}>();if(!challenge)return new Response("This verification link is invalid.",{status:400});if(challenge.verified_at)return new Response("This verification link has already been used.",{status:409});if(challenge.attempts>=MAX_ATTEMPTS)return new Response("Verification is temporarily locked.",{status:429});if(new Date(challenge.expires_at).getTime()<Date.now())return new Response("This verification link has expired. Please register again.",{status:410});const now=new Date().toISOString();const claim=await env.DB.prepare(`UPDATE identity_verification_challenges SET verified_at=?,attempts=attempts+1 WHERE id=? AND verified_at IS NULL AND attempts<? AND expires_at>?`).bind(now,challenge.id,MAX_ATTEMPTS,now).run();if(!claim.meta.changes)return new Response("This verification link is no longer valid. Please register again.",{status:409});if(challenge.channel==="guardian_email")await env.DB.prepare(`UPDATE participants SET email_verified_at=?,guardian_authorized_at=?,status='active',updated_at=? WHERE id=?`).bind(now,now,now,challenge.participant_id).run();else await env.DB.prepare(`UPDATE participants SET email_verified_at=?,status='active',updated_at=? WHERE id=?`).bind(now,now,challenge.participant_id).run();return new Response("Email verified. Return to Innovators World and select 'I have verified my email'.",{headers:{"content-type":"text/plain; charset=UTF-8"}})}catch(error){console.error("Email verification failed",error);return new Response("Unable to verify this email right now.",{status:500})}}

async function participantStatus(request:Request,env:Env):Promise<Response>{const id=new URL(request.url).searchParams.get("participant_id")?.trim()||"";if(!id)return fail("participant_id is required.");try{const participant=await env.DB.prepare(`SELECT id,participant_type,status,email_verified_at,guardian_authorized_at FROM participants WHERE id=? LIMIT 1`).bind(id).first<Participant>();if(!participant)return fail("Participant not found.",404);return json({status:"ok",participant:participantPublic(participant)})}catch(error){console.error("Participant status failed",error);return fail("Unable to retrieve participant status.",500)}}

async function startIWDA(request:Request,env:Env):Promise<Response>{try{const b=await body(request);const participantId=text(b.participant_id);const anonymousSessionId=text(b.anonymous_session_id);if(!participantId&&!anonymousSessionId)return fail("participant_id or anonymous_session_id is required.",401);if(anonymousSessionId&&(anonymousSessionId.length<16||anonymousSessionId.length>128))return fail("Invalid anonymous_session_id.",400);if(participantId){const participant=await env.DB.prepare(`SELECT id,status,email_verified_at,participant_type,guardian_authorized_at FROM participants WHERE id=? LIMIT 1`).bind(participantId).first<{id:string;status:string;email_verified_at:string|null;participant_type:ParticipantType;guardian_authorized_at:string|null}>();if(!participant)return fail("Participant not found.",404);const verified=Boolean(participant.email_verified_at)&&(participant.participant_type!=="minor"||Boolean(participant.guardian_authorized_at));if(!verified||participant.status!=="active")return fail("Participant email verification is incomplete.",403);const existing=await env.DB.prepare(`SELECT id FROM iwda_attempts WHERE participant_id=? AND status='started' ORDER BY started_at DESC LIMIT 1`).bind(participantId).first<{id:string}>();if(existing)return json({status:"ok",attempt_id:existing.id,assessment:"IWDA",resumed:true});const attemptId=crypto.randomUUID();await env.DB.prepare(`INSERT INTO iwda_attempts (id,user_id,anonymous_session_id,participant_id,status,started_at) VALUES (?,NULL,NULL,?,'started',datetime('now'))`).bind(attemptId,participantId).run();return json({status:"ok",attempt_id:attemptId,assessment:"IWDA",resumed:false})}const existing=await env.DB.prepare(`SELECT id FROM iwda_attempts WHERE anonymous_session_id=? AND status='started' ORDER BY started_at DESC LIMIT 1`).bind(anonymousSessionId).first<{id:string}>();if(existing)return json({status:"ok",attempt_id:existing.id,assessment:"IWDA",resumed:true});const attemptId=crypto.randomUUID();await env.DB.prepare(`INSERT INTO iwda_attempts (id,user_id,anonymous_session_id,participant_id,status,started_at) VALUES (?,NULL,?,NULL,'started',datetime('now'))`).bind(attemptId,anonymousSessionId).run();return json({status:"ok",attempt_id:attemptId,assessment:"IWDA",resumed:false})}catch(error){console.error("IWDA start failed",error);return fail("Unable to start IWDA.",500)}}

async function answer(request:Request,env:Env):Promise<Response>{try{const b=await body(request);const attemptId=text(b.attempt_id);const questionId=text(b.question_id);const value=text(b.answer).toUpperCase();if(!attemptId||!questionId||!value)return fail("attempt_id, question_id and answer are required.");if(!IWDA_QUESTIONS.some(q=>q.id===questionId))return fail("Invalid question_id.");if(!["A","B","C","D"].includes(value))return fail("answer must be A, B, C or D.");const attempt=await env.DB.prepare(`SELECT id,status FROM iwda_attempts WHERE id=? LIMIT 1`).bind(attemptId).first<{id:string;status:string}>();if(!attempt)return fail("IWDA attempt not found.",404);if(attempt.status!=="started")return fail("IWDA attempt is not active.",409);await env.DB.prepare(`DELETE FROM iwda_answers WHERE attempt_id=? AND question_id=?`).bind(attemptId,questionId).run();const answerId=crypto.randomUUID();await env.DB.prepare(`INSERT INTO iwda_answers (id,attempt_id,question_id,answer,created_at) VALUES (?,?,?,?,datetime('now'))`).bind(answerId,attemptId,questionId,value).run();return json({status:"ok",recorded:true,answer_id:answerId})}catch(error){console.error("IWDA answer failed",error);return fail("Unable to record answer.",500)}}

async function complete(request:Request,env:Env):Promise<Response>{try{const b=await body(request);const attemptId=text(b.attempt_id);if(!attemptId)return fail("attempt_id is required.");const existing=await env.DB.prepare(`SELECT id,attempt_id,user_id,innovation_readiness_index,traits,result_data,created_at FROM iwda_results WHERE attempt_id=? LIMIT 1`).bind(attemptId).first<Result>();if(existing)return json({status:"ok",completed:true,scoring_status:"complete",result:resultPublic(existing)});const attempt=await env.DB.prepare(`SELECT id,user_id,participant_id,anonymous_session_id,status FROM iwda_attempts WHERE id=? LIMIT 1`).bind(attemptId).first<Attempt>();if(!attempt)return fail("IWDA attempt not found.",404);if(attempt.status!=="started")return fail("IWDA attempt is not active.",409);if(!attempt.participant_id&&!attempt.anonymous_session_id)return fail("This IWDA attempt has no valid owner.",409);const answers=await env.DB.prepare(`SELECT question_id,answer FROM iwda_answers WHERE attempt_id=? ORDER BY created_at`).bind(attemptId).all<{question_id:string;answer:string}>();const rows=answers.results??[];const unique=new Set(rows.map(r=>r.question_id));if(unique.size!==IWDA_QUESTIONS.length)return fail(`IWDA requires all ${IWDA_QUESTIONS.length} questions to be answered before completion.`);const calculated=calculateIWDAResult(rows.map(r=>({question_id:r.question_id,answer:r.answer})));const resultId=crypto.randomUUID();const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO iwda_results (id,attempt_id,user_id,innovation_readiness_index,traits,result_data,created_at) VALUES (?,?,?,?,?,?,?)`).bind(resultId,attemptId,attempt.user_id,calculated.innovation_readiness_index,JSON.stringify(calculated.traits),JSON.stringify(calculated.result_data),now).run();await env.DB.prepare(`UPDATE iwda_attempts SET status='completed',completed_at=? WHERE id=?`).bind(now,attemptId).run();const saved:Result={id:resultId,attempt_id:attemptId,user_id:attempt.user_id,innovation_readiness_index:calculated.innovation_readiness_index,traits:JSON.stringify(calculated.traits),result_data:JSON.stringify(calculated.result_data),created_at:now};return json({status:"ok",completed:true,scoring_status:"complete",result:resultPublic(saved)})}catch(error){console.error("IWDA completion failed",error);return fail("Unable to complete IWDA.",500)}}

async function health(env:Env):Promise<Response>{try{await env.DB.prepare("SELECT 1 AS ok").first();const checks=await Promise.all(["participants","identity_verification_challenges","participant_consents","iwda_attempts"].map(async table=>{try{await env.DB.prepare(`SELECT 1 FROM ${table} LIMIT 1`).first();return[table,true] as const}catch{return[table,false] as const}}));return json({status:"ok",database:true,email_configured:Boolean(env.RESEND_API_KEY),email_provider:"resend",tables:Object.fromEntries(checks),service:"innovators-world-commercial"})}catch(error){console.error("Health check failed",error);return fail("Database unavailable.",503)}}

export default {async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url);if(url.pathname==="/api/health"&&request.method==="GET")return health(env);if(url.pathname==="/api/participants"&&request.method==="POST")return register(request,env);if(url.pathname==="/api/participants/status"&&request.method==="GET")return participantStatus(request,env);if(url.pathname==="/verify-email"&&request.method==="GET")return verifyEmail(request,env);if(url.pathname==="/api/iwda/questions"&&request.method==="GET")return json({status:"ok",assessment:"IWDA",version:"1.0",question_count:IWDA_QUESTIONS.length,questions:IWDA_QUESTIONS.map(({id,prompt})=>({id,prompt,options:["A","B","C","D"]}))});if(url.pathname==="/api/iwda/start"&&request.method==="POST")return startIWDA(request,env);if(url.pathname==="/api/iwda/answer"&&request.method==="POST")return answer(request,env);if(url.pathname==="/api/iwda/complete"&&request.method==="POST")return complete(request,env);if(env.ASSETS)return env.ASSETS.fetch(request);return new Response("Not found",{status:404})}};
